apiVersion: v1
kind: Namespace
metadata:
  name: podtato-kubectl
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-entry
  namespace: podtato-kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podtato-head-entry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podtato-head-entry
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.3.1
        # Keptn provides the option to add additional metadata which will be added to generated OTel traces
      annotations:
        keptn.sh/metadata: "owner=grabnerandi"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: ghcr.io/podtato-head/entry:latest  # 0.2.8 or latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: PODTATO_PORT
          value: "9000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-hat
  namespace: podtato-kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podtato-head-hat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podtato-head-hat
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.3.3
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image:  ghcr.io/podtato-head/hat:latest  # 0.2.8 or latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: PODTATO_PORT
              value: "9000"
---
apiVersion: lifecycle.keptn.sh/v1beta1
kind: KeptnAppContext
metadata:
  name: podtato-head
  namespace: podtato-kubectl
spec:
  metadata:
    commit-id: "1236"
    author: "grabnerandi"
  # Keptn allows you to specify spanLinks of "parent or related" traced activities, e.g: CI, prev-stage, promotion ...
  # spanLinks: 
  #  - "00-XXXXXXXXXXXXXXXXXXXXXXXXXXX" 